name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile add nixpkgs#devenv

    - name: Run tests
      shell: bash -c "nix develop --impure -c bash -- {0}"
      run: tests

    - name: Build release artifact
      shell: bash -c "nix develop --impure -c bash -- {0}"
      run: build

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: devenv-rust-test-${{ matrix.os }}
        path: target/release/devenv-rust-test
