name: "Build"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: nix run nixpkgs#devenv -- shell bash -- -e {0}

    steps:
    - uses: actions/checkout@v7
    - uses: DeterminateSystems/determinate-nix-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        use-flakehub: false
    - uses: DeterminateSystems/flake-checker-action@main

    - name: Build release artifact
      id: build
      run: |
        path=$(nix run nixpkgs#devenv -- build outputs.release | sed -n 's/.*"outputs.release": "\(.*\)"/\1/p')
        echo "path=$path" >> "$GITHUB_OUTPUT"

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: devenv-rust-test-${{ matrix.os }}
        path: ${{ steps.build.outputs.path }}/bin/*
